version: "3.8"

services:
  database:
    container_name: postgres_mbl
    image: postgres:16
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_mbl_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    image: demo:0.0.1
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
       SPRING_PROFILES_ACTIVE: local
       SPRING_DATASOURCE_WRITER_URL: jdbc:postgresql://postgres_mbl:5432/postgres
       SPRING_DATASOURCE_READER_URL: jdbc:postgresql://postgres_mbl:5432/postgres
       AWS_REGION: ap-northeast-2
       THC_PATH: /actuator/health/readiness
    healthcheck:
      test: ["CMD", "/workspace/health-check"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - database

volumes:
  postgres_mbl_data: