spring:
#  config:
#    import: optional:aws-secretsmanager:/secret/sample_pdmsdapne2
  datasource:
    writer:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5440/postgres
      username: postgres
      password: postgres_password
      hikari:
        maximum-pool-size: 5
        minimum-idle: 1
        connection-timeout: 15000
    reader:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5440/postgres
      username: postgres
      password: postgres_password
      hikari:
        maximum-pool-size: 5
        minimum-idle: 1
        connection-timeout: 15000

sample:
  id: ${id:test}
  password: ${password:test}

custom:
  token: ${token_value:U2FtcGxlIERldk9wcyB0b2tlbiB2YWx1ZXMK}



