spring:
  application:
    name: sample

logging:
  level:
    software.amazon.awssdk.auth: DEBUG
    software.amazon.jdbc: DEBUG
    root: DEBUG
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG
    com.mysql.cj: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
